# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Libretro.RetroArch.Nightly.64-bit
PackageVersion: 1.10.3
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://buildbot.libretro.com/stable/1.10.3/windows/x86_64/RetroArch-Win64-setup.exe
  InstallerSha256: 7fae3676a37a2b174692c9fc3d17b0c4db284966049e8630cf93a004aa588c60
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
ManifestType: installer
ManifestVersion: 1.1.0

